stages:
  - test
  - package
  - cleanup
  - toptl

image: livehybrid/splunk-appbuilder:version-3-acs
cache:
  key:
    files:
      - poetry.lock
  paths:
    - .venv/
    - venv/

before_script:
  - make git-init-submodules
  - make install


pytest:
  stage: test
  script:
    - make build
  artifacts:
    reports:
      junit: tmp/reports/**/*.xml
  tags:
    - DedicatedCICDRunner

package:
  stage: package
  script:
    - env
    - make dist
  artifacts:
    paths:
      - dist
    reports:
      junit: tmp/reports/**/*.xml
  tags:
    - DedicatedCICDRunner

cleanup_job:
  stage: cleanup
  script:
    - make down || true
  when: always
  tags:
    - DedicatedCICDRunner

upload:
  stage: toptl
  script:
    - env
    - make acsupload
  when: always
  tags:
    - DedicatedCICDRunner

